function dck -d "Docker helper aliases overview"
    echo "Docker Helper Functions"
    echo "======================"
    echo ""
    echo "  dsa    Stop all running containers"
    echo "  dka    Kill all running containers"
    echo "  dra    Remove all stopped containers"
    echo "  dria   Remove all images"
    echo "  dps    List running containers (pretty)"
    echo "  dpsa   List all containers (including stopped)"
    echo "  dimg   List images"
    echo "  dlg    Tail logs of a container           dlg <container>"
    echo "  dex    Exec into a container (bash/sh)    dex <container>"
    echo "  dprune Full system prune (volumes too)"
    echo "  dcu    docker compose up -d                dcu [services...]"
    echo "  dcd    docker compose down                 dcd [args...]"
    echo "  dcr    docker compose restart              dcr [services...]"
    echo "  dcl    docker compose logs -f              dcl [services...]"
    echo "  dcb    docker compose build                dcb [services...]"
    echo "  dvl    List volumes"
    echo "  dnl    List networks"
    echo "  dip    Get container IP address            dip <container>"
    echo "  dst    Container stats (snapshot)"
end
