function gth -d "Git helper aliases overview"
    echo "Git Helper Functions"
    echo "===================="
    echo ""
    echo "  gpo [flags]        Push current branch to origin"
    echo "  gs                 Status (short format)"
    echo "  ga <files...>      Add files to staging"
    echo "  gaa                Add all changes"
    echo "  gc <message>       Commit with message"
    echo "  gca <message>      Commit all tracked changes with message"
    echo "  gcm                Amend last commit (no edit)"
    echo "  gpl                Pull with rebase"
    echo "  gf                 Fetch all remotes"
    echo "  gb                 List branches"
    echo "  gbd <branch>       Delete branch"
    echo "  gsw <branch>       Switch branch"
    echo "  gsc <branch>       Switch and create new branch"
    echo "  gm <branch>        Merge branch into current"
    echo "  grb <branch>       Rebase onto branch"
    echo "  gl                 Log (oneline, graph, last 20)"
    echo "  gla                Log all branches (oneline, graph)"
    echo "  gd                 Diff unstaged changes"
    echo "  gds                Diff staged changes"
    echo "  gst                Stash changes"
    echo "  gstp               Stash pop"
    echo "  gstl               Stash list"
    echo "  gcp <hash>         Cherry-pick a commit"
    echo "  grh                Reset HEAD (soft)"
    echo "  grhh               Reset HEAD (hard)"
    echo "  gcl <url>          Clone a repository"
    echo "  gt <tag>           Create a tag"
    echo "  gbl <file>         Blame a file"
end
